config/routes.rb
Rails.application.routes.draw do
  root "codes#index"
  resources :codes, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/code.rb
class Code < ApplicationRecord
  # associations
  belongs_to :tag,  optional: true
end

app/models/tag.rb
class Tag < ApplicationRecord
  # associations
  has_many  :codes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/codes_controller.rb
class CodesController < ApplicationController

  def index
    @codes = Code.all
  end

  def show
  end

  def new
    @code = Code.new
  end

  def create
    @code = Code.new(code_params)
    @code.save
    redirect_to root_path
  end

  private
  def code_params
    params.require(:code).permit(:title, :error_content, :checked_content, :hypothesis, :result)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/codes_helper.rb
module CodesHelper
end

app/views/codes/_header.html.haml
%header.header
  %h1= link_to "Happycode" , root_path, class: "header-nav"
  %h3.header-nav
    %li= link_to "Code", new_code_path, class: "header-nav"
    %li= link_to "Delete", class: "header-nav"
    %li= link_to "Search", class: "header-nav"

app/views/codes/index.html.haml
=render "header"

%table
  %thead
    %tr
      //%th タグ
      %th タイトル
      %th エラーの内容
      %th 調べたこと
      %th 仮説
      %th 検証の結果
  %tbody
    - @codes.each do |code|
      %tr
        //%td=
        %td= code.title
        %td= code.error_content
        %td= code.checked_content
        %td= code.hypothesis
        %td= code.result

app/views/codes/new.html.haml
=render "header"

.codes-new
  = form_with model: @code, class: :for__contents, local: true do |f|
    = f.text_area :title, placeholder: "解決したいこと", class: :form__content, size: "200x2"
    = f.text_area :error_content, placeholder: "エラーの内容", class: :form__content, size: "200x5"
    = f.text_area :checked_content, placeholder: "調べたこと", class: :form__content, size: "200x5"
    = f.text_area :hypothesis, placeholder: "仮説", class: :form__content, size: "200x5"
    = f.text_area :result, placeholder: "検証の結果", class: :form__content, size: "200x5"
    = f.submit '投稿する', class: :form__btn

app/views/codes/show.html.haml
=render "header"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title HappyCode
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield